version: "3.8"

services:
  ros2-humble:
    image: osrf/ros:humble-desktop-full
    platform: linux/amd64
    container_name: ros2_humble_dev
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - DOCKER_CLI_EXPERIMENTAL=enabled

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/root/ros2_ws
      - ./setup_ros.sh:/setup_ros.sh:ro

    stdin_open: true
    tty: true
    working_dir: /root/ros2_ws
    entrypoint: /setup_ros.sh
    command: bash
